<a href="https://colab.research.google.com/github/EmmanuelUdeA/EcuacionesDif/blob/main/EcuacionesDif.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hola mundo MATERIA ECUACIONES DIFERENCIALES")

Hola mundo MATERIA ECUACIONES DIFERENCIALES


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sympy as sp


In [ ]:
#Algorithm Descomposition LU
def lu(A):

    #Get number rows of A
    n = A.shape[0]

    #Generation U and L initials
    U = A.copy()
    L = np.eye(n, dtype=np.double)

    #Initialization of loop
    for i in range(n):
        #For reduction factor
        factor = U[i+1:, i] / U[i, i]
        #Factor in position i+1, i
        L[i+1:, i] = factor
        #Multiplication of factor for row in U
        U[i+1:]=U[i+1:]-factor[:, np.newaxis] * U[i]

    return L, U

def asus(L, b):

    n = L.shape[0]
    y = np.zeros_like(b, dtype=np.double);


    y[0] = b[0] / L[0, 0]


    for i in range(1, n):
        y[i] = (b[i] - np.dot(L[i,:i], y[:i])) / L[i,i]

    return y

def rsus(U, y):


    n = U.shape[0]
    x = np.zeros_like(y, dtype=np.double)
    x[-1] = y[-1] / U[-1, -1]

    for i in range(n-2, -1,-1):
        x[i] = (y[i] - np.dot(U[i,i:], x[i:])) / U[i,i]

    return x

"""Si se quiere resolver la ecuación $Ax=b$, usando las tres ecuaciones en un solo paso, se hace"""

def lu_sol(A, b):

    l, u = lu(A)
    y = asus(l, b)
    return rsus(u, y)

A=np.array([[1,3,2],[-2,5,1], [4,12,5]])
b=np.array([6,4,21])

l,u=lu(A)
y=asus(l,b)
x=rsus(u,y)
x

lu_sol(A,b)

A@x

"""Factorización de Cholescky"""

def cholesky(A):

    n = A.shape[0]

    L = np.zeros((n, n), dtype=np.double)

    for k in range(n):

        L[k, k] = np.sqrt(A[k, k] - np.sum(L[k, :] ** 2))

        L[(k+1):, k] = (A[(k+1):, k] - L[(k+1):, :] @ L[k, :]) / L[k, k]

    return L

B=np.array([[1,-2,1], [-2,10,4], [1,4,9]])
B

lc=cholesky(B)
lc@lc.T

lc

np.linalg.cholesky(B)

lu(B)

def lu_inverse(A):

    n = A.shape[0]

    b = np.eye(n)
    Ainv = np.zeros((n, n))

    L, U = lu(A)

    for i in range(n):

        y = asus(L, b[i])

        Ainv[:, i] = rsus(U, y)

    return Ainv

np.round(lu_inverse(A),3)

np.linalg.inv(A)

A


array([[ 1,  3,  2],
       [-2,  5,  1],
       [ 4, 12,  5]])

In [ ]:
def cholesky(A):

    n = A.shape[0]

    L = np.zeros((n, n), dtype=np.double)

    for k in range(n):

        L[k, k] = np.sqrt(A[k, k] - np.sum(L[k, :] ** 2))

        L[(k+1):, k] = (A[(k+1):, k] - L[(k+1):, :] @ L[k, :]) / L[k, k]

    return L

A = np.array([[6,-1,-5],[-1,1,1],[-5,1,5]])
A

cholesky(A)



array([[ 2.44948974,  0.        ,  0.        ],
       [-0.40824829,  0.91287093,  0.        ],
       [-2.04124145,  0.18257419,  0.89442719]])

In [ ]:
A=np.array([[3, 5, -6, 7, 5],
            [5, -5, -2, 3, 6],
            [1, -3, 7, -5, 8],
            [2, -1, 1, -4, -9],
            [-7, -2, 8, -1, -1]])
A

B=np.array ([67,71,54,87,61])
B

lu(A)


lu_sol(A,B)

l,u=lu(A)
y=asus(l,B)
y


array([ 67.        , -40.66666667,  44.17948718,  40.11965812,
       309.53846154])

In [ ]:
"""#Método de Jacobi"""

A=np.array([[7, 2, 4], [-3,9,5], [1,1,3]])
b=np.array([13,11,5])
sup=np.array([0,0,0])

import math

def jacobi(A,b,N=100,x=None):
      it=0
      if x is None:
        x = np.zeros(len(A[0]))

      D = np.diag(A)
      R = A - np.diagflat(D)

      for i in range(N):
        x = (b - np.dot(R,x)) / D
        it=it+1
        print(it,x)



def GS(A,b,N,x=None):
      if x is None:
        x = np.zeros(len(A[0]))
      DL = np.tril(A)
      U = np.triu(A)-np.diagflat(np.diag(A))
      for i in range(N):
          error1= x[0]
          error2= x[1]
          error3= x[2]
          x = np.dot(np.linalg.inv(DL),(b - np.dot(U,x)))
          errorX1= round(math.fabs((x[0]-error1)/x[0])*100, 2)
          errorX2= round(math.fabs((x[1]-error2)/x[1])*100, 2)
          errorX3= round(math.fabs((x[2]-error3)/x[2])*100, 2)
          print(i+1, 'x11=', round(x[0], 7), 'x22=', round(x[1], 7), 'x33=',
                round(x[2], 7), 'eX1=', errorX1, 'eX2=', errorX2, 'eX3=', errorX3)

GS(A,b,20,sup)


1 x11= 1.8571429 x22= 1.8412698 x33= 0.4338624 eX1= 100.0 eX2= 100.0 eX3= 100.0
2 x11= 1.0831444 x22= 1.3422357 x33= 0.8582067 eX1= 71.46 eX2= 37.18 eX3= 49.45
3 x11= 0.9832432 x22= 1.0731885 x33= 0.9811895 eX1= 10.16 eX2= 25.07 eX3= 12.53
4 x11= 0.9898379 x22= 1.0070629 x33= 1.0010331 eX1= 0.67 eX2= 6.57 eX3= 1.98
5 x11= 0.9973917 x22= 0.9985566 x33= 1.0013506 eX1= 0.76 eX2= 0.85 eX3= 0.03
6 x11= 0.9996406 x22= 0.9991299 x33= 1.0004098 eX1= 0.22 eX2= 0.06 eX3= 0.09
7 x11= 1.0000144 x22= 0.9997771 x33= 1.0000695 eX1= 0.04 eX2= 0.06 eX3= 0.03
8 x11= 1.000024 x22= 0.9999694 x33= 1.0000022 eX1= 0.0 eX2= 0.02 eX3= 0.01
9 x11= 1.0000075 x22= 1.0000013 x33= 0.9999971 eX1= 0.0 eX2= 0.0 eX3= 0.0
10 x11= 1.0000013 x22= 1.0000021 x33= 0.9999989 eX1= 0.0 eX2= 0.0 eX3= 0.0
11 x11= 1.0000001 x22= 1.0000006 x33= 0.9999998 eX1= 0.0 eX2= 0.0 eX3= 0.0
12 x11= 0.9999999 x22= 1.0000001 x33= 1.0 eX1= 0.0 eX2= 0.0 eX3= 0.0
13 x11= 1.0 x22= 1.0 x33= 1.0 eX1= 0.0 eX2= 0.0 eX3= 0.0
14 x11= 1.0 x22= 1.0 x33= 1

In [ ]:
A = np.array([[5,3,-1],[-2,4,1],[2,-5,8]])
A

B = np.array([51,18,41])
B

sup = np.array([0,0,0])

GS(A,B,20,sup)

1 x11= 10.2 x22= 9.6 x33= 8.575 eX1= 100.0 eX2= 100.0 eX3= 100.0
2 x11= 6.155 x22= 5.43375 x33= 6.9823438 eX1= 65.72 eX2= 76.67 eX3= 22.81
3 x11= 8.3362187 x22= 6.9225234 x33= 7.3675225 eX1= 26.17 eX2= 21.51 eX3= 5.23
4 x11= 7.5199904 x22= 6.4181146 x33= 7.256324 eX1= 10.85 eX2= 7.86 eX3= 1.53
5 x11= 7.800396 x22= 6.586117 x33= 7.2912241 eX1= 3.59 eX2= 2.55 eX3= 0.48
6 x11= 7.7065746 x22= 6.5304813 x33= 7.2799071 eX1= 1.22 eX2= 0.85 eX3= 0.16
7 x11= 7.7376927 x22= 6.5488695 x33= 7.2836203 eX1= 0.4 eX2= 0.28 eX3= 0.05
8 x11= 7.7274023 x22= 6.5427961 x33= 7.282397 eX1= 0.13 eX2= 0.09 eX3= 0.02
9 x11= 7.7308017 x22= 6.5448016 x33= 7.2828006 eX1= 0.04 eX2= 0.03 eX3= 0.01
10 x11= 7.7296791 x22= 6.5441394 x33= 7.2826674 eX1= 0.01 eX2= 0.01 eX3= 0.0
11 x11= 7.7300498 x22= 6.5443581 x33= 7.2827113 eX1= 0.0 eX2= 0.0 eX3= 0.0
12 x11= 7.7299274 x22= 6.5442859 x33= 7.2826968 eX1= 0.0 eX2= 0.0 eX3= 0.0
13 x11= 7.7299678 x22= 6.5443097 x33= 7.2827016 eX1= 0.0 eX2= 0.0 eX3= 0.0
14 x11= 7.7299545 x22=

In [ ]:
from sympy import *

from scipy.interpolate import lagrange

x1 = np.array([-1,3,4,-2,5])
y1 = np.array([2,4,-1,-2,3])
poly = lagrange(x1, y1)

poly

x = np.linspace(-3,5,200)
y = [np.polyval(poly, i) for i in x]
plt.figure(figsize=(10,8))
plt.scatter(x1,y1, color='r', label='initpoint')
plt.title('Polynomial Lagrange')
plt.axvline(0, color='g', ls='--')
plt.axhline(0, color='g', ls='--')
plt.plot(x,y,label='intLagPoly')
plt.legend()
plt.grid()
plt.ylim(-15,15)
plt.show()

def lint(x, y, xi):

    n = len(x)
    if n != len(y):
        raise ValueError("x and y must have the same length")

    # Compute the Lagrange basis polynomials
    L = []
    for j in range(n):
        lj = 1.0
        for m in range(n):
            if m != j:
                lj *= (xi - x[m])/(x[j] - x[m])
        L.append(sp.expand(lj))


    # Compute the Lagrange polynomial interpolation
    p = 0.0
    for j in range(n):
        p += sp.expand(y[j]*L[j])

    return p, L

from sympy.plotting import plot
from sympy.plotting.plot import MatplotlibBackend, Plot


def get_sympy_subplots(plot:Plot):
    backend = MatplotlibBackend(plot)

    backend.process_series()
    backend.fig.tight_layout()
    return backend.fig, backend.ax[0]

x=sp.symbols('x')
poly1, L1=lint(x1,y1,x)

L1

poly1

plot(poly1, xlim=(-5, 10), ylim=(-15,15), nb_of_points=1000, size=(10,8))

# plot from backend
fig, axe = get_sympy_subplots(p)
# add additional plots
axe.plot(x1, y1, "o", color='r')
fig.savefig("plot_from_figure")

f=sp.exp(x)+3/x**2+0.0047
f

sp.plot(f, ylim=(-5,15))

x2=np.random.uniform(-1,1,5)
x2

y2=np.array([f.subs(x,i) for i in x2])
y2

P,L=lint(x2,y2,x)
P

P1=plot(P, f, ylim=(-45,45), size=(8,8), show=False)
P1[0].line_color = 'green'

P1.show()

fig, axe =get_sympy_subplots(P1)
axe.plot(x2, y2, "o", color='r')


In [ ]:
from scipy.interpolate import lagrange

x1 = np.array([-1,2,0.5,6,9.5, 0.89481])
y1 = np.array([5.71875, 0.88581,12.607, 0.08628, 0.03379, 4.15597])
poly = lagrange(x1, y1)

poly

x = np.linspace(-3,10,200)
y = [np.polyval(poly, i) for i in x]
plt.figure(figsize=(10,8))
plt.scatter(x1,y1, color='r', label='initpoint')
plt.title('Polynomial Lagrange')
plt.axvline(0, color='g', ls='--')
plt.axhline(0, color='g', ls='--')
plt.plot(x,y,label='intLagPoly')
plt.legend()
plt.ylim(-75,75)
plt.show()

In [ ]:
import numpy as np

def rk4_method(f, x0, y0, h, x_target):
    x = x0
    y = y0

    while x < x_target:
        k1 = h * f(x, y)
        k2 = h * f(x + 0.5 * h, y + 0.5 * k1)
        k3 = h * f(x + 0.5 * h, y + 0.5 * k2)
        k4 = h * f(x + h, y + k3)

        y += (k1 + 2 * k2 + 2 * k3 + k4) / 6
        x += h

    return y

def f(x, y):
    return (3 * y + 2 * x * y) / (x**2)

x0 = 1
y0 = 1/2
h = 0.1
x_target = 3.1

y_target = rk4_method(f, x0, y0, h, x_target)
print("El valor de y(3.1) utilizando RK4 con h = 0.1 es:", y_target)

El valor de y(3.1) utilizando RK4 con h = 0.1 es: 36.65835505519604
